package mod.trindade.dev.ui.theme

import androidx.compose.ui.graphics.Color

import com.sketchware.remod.R

object LightColors {
    val primary = Color(0xFF006493)
    val onPrimary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFFCAE6FF)
    val onPrimaryContainer = Color(0xFF001E30)
    val primaryFixed = Color(0xFFCAE6FF)
    val primaryFixedDim = Color(0xFF001E30)
    val onPrimaryFixed = Color(0xFF001E30)
    val onPrimaryFixedVariant = Color(0xFF004B70)
    val secondary = Color(0xFF50606E)
    val onSecondary = Color(0xFFFFFFFF)
    val secondaryContainer = Color(0xFFD3E5F6)
    val onSecondaryContainer = Color(0xFF0C1D29)
    val secondaryFixed = Color(0xFFD3E5F6)
    val secondaryFixedDim = Color(0xFFB7C9D9)
    val onSecondaryFixed = Color(0xFF0C1D29)
    val onSecondaryFixedVariant = Color(0xFF384956)
    val tertiary = Color(0xFF006493)
    val onTertiary = Color(0xFFFFFFFF)
    val tertiaryContainer = Color(0xFFCAE6FF)
    val onTertiaryContainer = Color(0xFF001E30)
    val tertiaryFixed = Color(0xFFCAE6FF)
    val tertiaryFixedDim = Color(0xFF8DCDFF)
    val onTertiaryFixed = Color(0xFF001E30)
    val onTertiaryFixedVariant = Color(0xFF004B70)
    val error = Color(0xFFBA1A1A)
    val errorContainer = Color(0xFFFFDAD6)
    val onError = Color(0xFFFFFFFF)
    val onErrorContainer = Color(0xFF410002)
    val background = Color(0xFFFCFCFF)
    val onBackground = Color(0xFF1A1C1E)
    val surface = Color(0xFFFCFCFF)
    val onSurface = Color(0xFF1A1C1E)
    val surfaceVariant = Color(0xFFDDE3EA)
    val onSurfaceVariant = Color(0xFF41474D)
    val outline = Color(0xFF72787E)
    val inverseOnSurface = Color(0xFFF0F0F3)
    val inverseSurface = Color(0xFF2E3133)
    val inversePrimary = Color(0xFF8DCDFF)
    val shadow = Color(0xFF000000)
    val surfaceTint = Color(0xFF006493)
    val outlineVariant = Color(0xFFC1C7CE)
    val scrim = Color(0xFF000000)
    val greenContainer = Color(0xFF7AFBB7)
    val amberContainer = Color(0xFFFFDF9E)
    val greenOnContainer = Color(0xFF002111)
    val amberOnContainer = Color(0xFF261A00)
}

object DarkColors {
    val primary = Color(0xFF8DCDFF)
    val onPrimary = Color(0xFF00344F)
    val primaryContainer = Color(0xFF004B70)
    val onPrimaryContainer = Color(0xFFCAE6FF)
    val primaryFixed = Color(0xFFCAE6FF)
    val primaryFixedDim = Color(0xFF8DCDFF)
    val onPrimaryFixed = Color(0xFF001E30)
    val onPrimaryFixedVariant = Color(0xFF004B70)
    val secondary = Color(0xFFB7C9D9)
    val onSecondary = Color(0xFF22323F)
    val secondaryContainer = Color(0xFF384956)
    val onSecondaryContainer = Color(0xFFD3E5F6)
    val secondaryFixed = Color(0xFFD3E5F6)
    val secondaryFixedDim = Color(0xFFB7C9D9)
    val onSecondaryFixed = Color(0xFF0C1D29)
    val onSecondaryFixedVariant = Color(0xFF384956)
    val tertiary = Color(0xFF8DCDFF)
    val onTertiary = Color(0xFF00344F)
    val tertiaryContainer = Color(0xFF004B70)
    val onTertiaryContainer = Color(0xFFCAE6FF)
    val tertiaryFixed = Color(0xFFCAE6FF)
    val tertiaryFixedDim = Color(0xFF8DCDFF)
    val onTertiaryFixed = Color(0xFF001E30)
    val onTertiaryFixedVariant = Color(0xFF004B70)
    val error = Color(0xFFFFB4AB)
    val errorContainer = Color(0xFF93000A)
    val onError = Color(0xFF690005)
    val onErrorContainer = Color(0xFFFFDAD6)
    val background = Color(0xFF1A1C1E)
    val onBackground = Color(0xFFE2E2E5)
    val surface = Color(0xFF1A1C1E)
    val onSurface = Color(0xFFE2E2E5)
    val surfaceVariant = Color(0xFF41474D)
    val onSurfaceVariant = Color(0xFFC1C7CE)
    val outline = Color(0xFF8B9198)
    val inverseOnSurface = Color(0xFF1A1C1E)
    val inverseSurface = Color(0xFFE2E2E5)
    val inversePrimary = Color(0xFF006493)
    val shadow = Color(0xFF000000)
    val surfaceTint = Color(0xFF8DCDFF)
    val outlineVariant = Color(0xFF41474D)
    val scrim = Color(0xFFFFFFFF)
    val greenContainer = Color(0xFF00504A)
    val amberContainer = Color(0x5B4300)
    val greenOnContainer = Color(0xFF72F7E9)
    val amberOnContainer = Color(0xFFFFDF9E)
}